"""empty message

Revision ID: 78673797c6d9
Revises: 
Create Date: 2020-06-03 02:07:56.296893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78673797c6d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
